-- ModzVerse Training Schools (7 schools, v1.0.0)

INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (1, 'Doragon Dojo', 4, 'Japan', 'The Doragon Dojo is the developmental training school for RAIBARAZU''s A-brand.', 'Training', 3, 75, 'Pure Wrestling', '1980-01-01', 1);
INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (2, 'Fenikkusu Flight School', 4, 'Japan', 'The Fenikkusu Flight School is RAIBARAZU''s B-brand developmental school.', 'Training', 2, 60, 'Pure Wrestling', '1980-01-01', 1);
INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (3, 'The Chicago Wrestling Academy', 1, 'United States', 'The Chicago Wrestling Academy is the developmental territory for Chicago Show.', 'Training', 3, 70, 'Sports Entertainment', '1980-01-01', 1);
INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (4, 'La Academia de Mariposas', 2, 'Mexico', 'Lucha Bellas'' training school teaching sacred lucha libre traditions.', 'Training', 2, 65, 'Lucha Libre', '1980-01-01', 1);
INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (5, 'Escuela de Tradicion Mexicana', 3, 'Mexico', 'Lucha MEX''s developmental territory emphasizing old-school fundamentals.', 'Training', 3, 70, 'Traditional', '1980-01-01', 1);
INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (6, 'Osaka Joshi Developmental', 5, 'Japan', 'Osaka Joshi''s training school for future stars.', 'Training', 2, 68, 'Kings Road', '1980-01-01', 1);
INSERT INTO trainingSchools (schoolID, name, ownerPromotion, basedIn, description, type, size, reputation, focusStyle, foundedDate, isOpen) VALUES (7, 'Valhalla Training Ground', 6, 'Japan', 'Valkyrie Project''s developmental school. The smallest in the ModzVerse.', 'Training', 1, 55, 'Kings Road', '1980-01-01', 1);
