-- ModzVerse Storylines + Match Stories + Angle Templates + Template Beats (v1.0.0)

-- STORYLINES (21)

INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (1, 'The Ace vs The Iron Fist', 4, '2025-01-01', 1, 'Ryuga the Apex vs Kuroda the Iron Fist. The defining rivalry of RAIBARAZU.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (2, 'Phoenix vs Dragon - Brand Supremacy', 4, '2025-01-01', 1, 'The Phoenix Academy vs The Iron Court. A faction war for control of the Doragon brand.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (3, 'The Call-Up Quest', 4, '2025-01-01', 1, 'Yuya Ueno is on the verge of being called up to Doragon. The Iron Court tries to sabotage.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (4, 'Monster Pack Rampage', 4, '2025-01-01', 1, 'The Monster Pack vs The Fenikkusu Vanguard on the B-brand.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (5, 'The Dream Tag Team Tournament', 4, '2025-01-01', 1, 'A tournament to determine the #1 tag team contender. Apex Phoenix vs Iron Fist Cobra.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (6, 'Money vs Heart', 1, '2025-01-01', 1, 'Max Thunderford vs Vincent Viceroy. Corporate greed vs working-class heart.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (7, 'Viceroy Syndicate vs Chicago Heart', 1, '2025-01-01', 1, 'Corporate heel stable vs blue-collar face stable.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (8, 'Women''s Division: Queen vs Diamond', 1, '2025-01-01', 1, 'Roxy Ravencroft vs Diamond Diane.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (9, 'The Showman''s Descent', 1, '2025-01-01', 1, 'The Showman Shelton''s mental health arc.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (10, 'Mask vs Mask - Luchastica Main Event', 2, '2025-01-01', 1, 'La Reina Escarlata vs Mariposa Dorada. The loser loses their mask.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (11, 'El Consejo vs Las Tecnicas', 2, '2025-01-01', 1, 'Heel stable vs face stable. A war for the soul of Lucha Bellas.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (12, 'The Beast Unleashed', 2, '2025-01-01', 1, 'Valkiria Negra vs Mariposa Dorada. Can technique overcome raw power?');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (13, 'Honor vs Darkness', 3, '2025-01-01', 1, 'El Toro Bravo vs El Diablo Rojo.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (14, 'La Oscuridad vs La Tradicion', 3, '2025-01-01', 1, 'The darkness stable vs the tradition stable.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (15, 'The Mask Collection', 3, '2025-01-01', 1, 'El Diablo Rojo collects masks from defeated technicos.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (16, 'Ace vs Queen - The Crown Jewel', 5, '2025-01-01', 1, 'Haruka Honjou vs Miyako Tsujimoto.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (17, 'The Royal Court vs The Future', 5, '2025-01-01', 1, 'Heel aristocracy vs rising stars.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (18, 'The Monster''s Path', 5, '2025-01-01', 1, 'Rina Kurosawa vs Haruka Honjou.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (19, 'The AEGIS LEAGUE Tournament', 6, '2025-01-01', 1, 'Freya Asagiri vs Skull Valkyrie for the vacant title.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (20, 'Valhalla''s Chosen vs The Wild Hunt', 6, '2025-01-01', 1, 'Face stable vs heel stable.');
INSERT INTO storylines (storylineID, storylineName, promotionID, startDate, active, overview) VALUES (21, 'The Shieldmaiden''s Trial', 6, '2025-01-01', 1, 'Freya Asagiri vs Hikari Tonegawa. Can friendship survive competition?');

-- MATCH STORIES (8)

INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (1, 'Standard Singles Match', 'A standard one-on-one singles match.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (2, 'Hardcore Brawl', 'A no-disqualification match with weapons.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (3, 'Tag Team Match', 'A standard tag team match with hot tags.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (4, 'Lucha Libre Match', 'A high-flying lucha libre match.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (5, 'Monster Squash', 'A dominant squash match.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (6, 'Championship Match', 'A high-stakes championship match.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (7, 'Mask vs Mask (Luchastica)', 'The loser loses their mask.', '', '', '', '', 1.0, 5, '');
INSERT INTO matchstories (matchstoryID, name, description, statWeights, requirements, styleModifiers, riskModifiers, popGainModifier, decayRate, lengthBonus) VALUES (8, 'Iron Man Match', 'A 30-minute iron man match.', '', '', '', '', 1.0, 5, '');

-- ANGLE TEMPLATES (15)

INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (1, 'Champion''s Address', 'Champion addresses the crowd', 'Champion','','','','','','','', 'Champion''s Address', 'Champion addresses the crowd', 'promo');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (2, 'Surprise Attack', 'Heel attacks face from behind', 'Victim','Attacker','','','','','','', 'Surprise Attack', 'Heel attacks face from behind', 'attack');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (3, 'Face-to-Face Confrontation', 'Two rivals face off', 'Wrestler 1','Wrestler 2','','','','','','', 'Face-to-Face Confrontation', 'Two rivals face off', 'confrontation');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (4, 'Championship Celebration', 'Champion celebrates', 'Champion','','','','','','','', 'Championship Celebration', 'Champion celebrates', 'celebration');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (5, 'Backstage Ambush', 'Heel ambushes face backstage', 'Victim','Attacker','','','','','','', 'Backstage Ambush', 'Heel ambushes face backstage', 'backstage');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (6, 'Stable Formation', 'New stable forms', 'Leader','Member 1','Member 2','','','','','', 'Stable Formation', 'New stable forms', 'stable');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (7, 'Betrayal', 'Tag partner turns', 'Victim','Betrayer','','','','','','', 'Betrayal', 'Tag partner turns', 'betrayal');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (8, 'Mask Unmasking', 'Ruda unmasks technica', 'Technica','Ruda','','','','','','', 'Mask Unmasking', 'Ruda unmasks technica', 'lucha');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (9, 'Call-Up Announcement', 'B-brand worker called up', 'B-Brand Worker','A-Brand Ace','','','','','','', 'Call-Up Announcement', 'B-brand worker called up', 'call-up');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (10, 'Contract Signing', 'Rivals sign contract', 'Rival 1','Rival 2','','','','','','', 'Contract Signing', 'Rivals sign contract', 'contract');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (11, 'Farewell Address', 'Retiring wrestler says goodbye', 'Retiring Wrestler','','','','','','','', 'Farewell Address', 'Retiring wrestler says goodbye', 'retirement');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (12, 'Heel Turn', 'Face turns heel', 'Turning Wrestler','Opponent','','','','','','', 'Heel Turn', 'Face turns heel', 'heel-turn');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (13, 'Title Vacate', 'Champion vacates due to injury', 'Champion','','','','','','','', 'Title Vacate', 'Champion vacates due to injury', 'vacate');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (14, 'Return from Injury', 'Surprise return', 'Returning Wrestler','','','','','','','', 'Return from Injury', 'Surprise return', 'return');
INSERT INTO angleTemplates (templateID, templateName, templateDescription, worker1, worker2, worker3, worker4, worker5, worker6, worker7, worker8, angleName, angleDescription, tags) VALUES (15, 'Stable Disintegration', 'Stable breaks apart', 'Leader','Member 1','Member 2','','','','','', 'Stable Disintegration', 'Stable breaks apart', 'breakup');

-- TEMPLATE BEATS (29)

INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (1, 1, 'Entrance', 30, 'Champion enters', '', '', 'Normal', 'Championship', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (2, 1, 'Promo', 60, 'Champion speaks', '', '', 'Standard', 'Championship', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (3, 1, 'Challenge', 30, 'Challenger appears', '', '', 'Music hit', 'Video', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (4, 2, 'Setup', 30, 'Victim interviewed', '', '', 'Backstage', 'Ringside', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (5, 2, 'Attack', 15, 'Attacker strikes', '', '', 'From behind', 'Weapon', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (6, 2, 'Aftermath', 30, 'Officials intervene', '', '', 'Pull apart', 'Medical', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (7, 3, 'Entrance 1', 30, 'First wrestler enters', '', '', 'Normal', 'Entourage', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (8, 3, 'Entrance 2', 30, 'Second wrestler enters', '', '', 'Normal', 'Interrupts', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (9, 3, 'Staredown', 30, 'Face to face', '', '', 'Silent', 'Trash talk', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (10, 3, 'Shove', 15, 'Escalation', '', '', 'Push', 'Punch', 4);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (11, 4, 'Celebration', 60, 'Champion celebrates', '', '', 'Turnbuckle', 'Crowd', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (12, 4, 'Crowd', 30, 'Crowd appreciates', '', '', 'Cheering', 'Ovation', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (13, 5, 'Setup', 30, 'Victim warming up', '', '', 'Backstage', 'Locker room', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (14, 5, 'Ambush', 15, 'Weapon attack', '', '', 'Chair', 'Kendo stick', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (15, 5, 'Taunt', 30, 'Attacker taunts', '', '', 'Verbal', 'Physical', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (16, 6, 'Leader speaks', 30, 'Stable leader', '', '', 'Unification', 'Dominance', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (17, 6, 'Member 1', 15, 'First member joins', '', '', 'Voluntary', 'Recruited', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (18, 6, 'Member 2', 15, 'Second member joins', '', '', 'Voluntary', 'Recruited', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (19, 7, 'Victim celebrates', 30, 'Partner celebrates', '', '', 'Tag win', 'Singles', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (20, 7, 'Betrayal', 15, 'Betrayer strikes', '', '', 'Finisher', 'Weapon', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (21, 7, 'Speech', 30, 'Betrayer explains', '', '', 'Jealousy', 'Ambition', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (22, 8, 'Trap', 30, 'Ruda traps technica', '', '', 'Corner', 'Ropes', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (23, 8, 'Mask grab', 15, 'Ruda reaches for mask', '', '', 'Slow', 'Rapid', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (24, 8, 'Save', 15, 'Officials intervene', '', '', 'Referee', 'Multiple', 3);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (25, 9, 'B-Brand', 30, 'Worker in ring', '', '', 'Alone', 'With mentor', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (26, 9, 'A-Brand', 30, 'Ace enters', '', '', 'Handshake', 'Staredown', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (27, 10, 'Sign 1', 15, 'First signs', '', '', 'Aggressive', 'Calm', 1);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (28, 10, 'Sign 2', 15, 'Second signs', '', '', 'Aggressive', 'Calm', 2);
INSERT INTO templateBeats (beatID, templateID, beatType, beatLength, group1, group2, group3, option1, option2, beatIndex) VALUES (29, 10, 'Brawl', 30, 'Table flip', '', '', 'Security', 'Backstage', 3);
