-- ============================================================
-- ModzVerse — Storylines + Match Stories + Angle Templates + Template Beats
-- Fully fictional content — no real-world wrestling content
-- Generated for v1.0.0 (content complete)
-- ============================================================

-- ============================================================
-- STORYLINES (21 storylines across 6 promotions)
-- ============================================================

INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (1, 'The Ace vs The Iron Fist', 4, 'Feud', 1001, 1002, 'The defining rivalry of RAIBARAZU. Ryūga the Apex (Doragon ace, face) vs Kuroda the Iron Fist (Doragon ace, heel). Two aces, one brand, one ring. This feud has been simmering since the brand split and will culminate at Battle of Rivals. The Iron Court has been interfering on Kuroda''s behalf, but Ryūga refuses to back down.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (2, 'Phoenix vs Dragon — Brand Supremacy', 4, 'Stable War', 1004, 1002, 'The Phoenix Academy (face, led by Suzaku the Phoenix) vs The Iron Court (heel, led by Kuroda the Iron Fist). A faction war for control of the Doragon brand. The winner determines who books the main event of Battle of Rivals.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (3, 'The Call-Up Quest', 4, 'Mentorship', 1016, 1001, 'Yuya Ueno (Fenikkusu ace) is on the verge of being called up to Doragon. Ryūga the Apex has taken him under his wing, but The Iron Court is trying to sabotage the call-up to prevent a new face threat. Yuya must prove himself on Fenikkusu shows while fending off heel interference.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (4, 'Monster Pack Rampage', 4, 'Stable War', 1027, 1016, 'The Monster Pack (heel, led by Wolf Hashimoto) vs The Fenikkusu Vanguard (face, led by Yuya Ueno). The monsters are terrorizing the B-brand, and the Vanguard is the only thing standing between them and total chaos. Wolf wants to break Yuya before he can be called up.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (5, 'The Dream Tag Team Tournament', 4, 'Feud', 1001, 1002, 'A tournament to determine the #1 contender for a future tag team championship. Apex Phoenix vs Iron Fist Cobra in the finals — the ace dream team vs the heel nightmare team. The winner gets bragging rights and a future title shot.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (6, 'Money vs Heart', 1, 'Feud', 2001, 2002, 'Max Thunderford (face franchise player) vs Vincent Viceroy (heel millionaire). The Viceroy Syndicate has been buying off referees and sabotaging Max''s matches. Max must overcome corporate corruption to reclaim his spot at the top.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (7, 'The Viceroy Syndicate vs The Chicago Heart', 1, 'Stable War', 2002, 2001, 'The corporate heel stable (Viceroy Syndicate) vs the blue-collar face stable (Chicago Heart). A war for the soul of Chicago Show — corporate greed vs working-class heart. Every week brings a new confrontation.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (8, 'Women's Division: Queen vs Diamond', 1, 'Feud', 2004, 2005, 'Roxy Ravencroft (heel queen) vs Diamond Diane (cocky face). Roxy believes she''s royalty; Diamond believes she''s the future. Their rivalry has elevated the women''s division to main event status on weekly TV.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (9, 'The Showman's Descent', 1, 'Betrayal', 2006, 2013, 'The Showman Shelton (unstable face) has been losing his grip on reality. Flash Freddy, his tag team partner, is concerned. The storyline explores Shelton''s mental health and whether Freddy can save him — or whether Shelton will turn heel.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (10, 'Mask vs Mask — Luchastica Main Event', 2, 'Title', 3001, 3002, 'La Reina Escarlata (heel queen, masked) vs Mariposa Dorada (face ace, masked). The most dramatic match in lucha libre — mask vs mask. The loser loses their mask and their identity. This is the Luchastica main event.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (11, 'El Consejo vs Las Técnicas', 2, 'Stable War', 3001, 3002, 'The heel stable (El Consejo Escarlata, led by La Reina) vs the face stable (Las Técnicas Puras, led by Mariposa Dorada). A war for the soul of Lucha Bellas — the rudas want to rule through fear; the técnicas want to preserve the sacred tradition of the mask.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (12, 'The Beast Unleashed', 2, 'Feud', 3003, 3002, 'Valkiria Negra (monster heel) has been destroying technicas one by one. Mariposa Dorada is the only one who can stop her — but the size difference is enormous. Can technique overcome raw power?', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (13, 'Honor vs Darkness', 3, 'Feud', 4001, 4002, 'El Toro Bravo (face ace) vs El Diablo Rojo (heel ace). The brave bull vs the red devil. The most personal feud in Lucha MEX — Diablo has been unmasking Toro''s allies one by one, and Toro has sworn revenge.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (14, 'La Oscuridad vs La Tradición', 3, 'Stable War', 4002, 4001, 'The darkness stable (La Oscuridad, led by El Diablo Rojo) vs the tradition stable (La Tradición, led by El Toro Bravo). A war for the future of Mexican wrestling — the old ways vs the dark new path.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (15, 'The Mask Collection', 3, 'Title', 4002, 4003, 'El Diablo Rojo has been collecting masks from defeated technicos. His next target: Caballero Blanco''s pride. If Diablo wins, Caballero must surrender his mask. The white knight''s honor is on the line.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (16, 'Ace vs Queen — The Crown Jewel', 5, 'Title', 5001, 5002, 'Haruka Honjou (face ace) vs Miyako Tsujimoto (heel queen). The ace vs the queen — the defining rivalry of Osaka Joshi. Two main eventers who have been circling each other for years. This is the feud that will define the promotion''s first canon year.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (17, 'The Royal Court vs The Future', 5, 'Stable War', 5002, 5001, 'The heel aristocracy (Royal Court, led by Miyako) vs the face mentoring stable (The Future, led by Haruka). A generational war — the established queens vs the rising stars. The Future wants to dethrone the Court.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (18, 'The Monster's Path', 5, 'Feud', 5003, 5001, 'Rina Kurosawa (monster heel) has been destroying everyone in her path. Haruka Honjou is the only one who can stop her — but Rina is bigger, stronger, and more violent. Can the ace overcome the monster?', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (19, 'The AEGIS LEAGUE Tournament', 6, 'Title', 6001, 6002, 'Freya Asagiri (face contender) vs Skull Valkyrie (heel contender). The AEGIS LEAGUE championship is vacant — a tournament will determine the first champion. Freya and Skull are on a collision course for the finals at Valhalla.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (20, 'Valhalla's Chosen vs The Wild Hunt', 6, 'Stable War', 6001, 6002, 'The face stable (Valhalla''s Chosen, led by Freya) vs the heel stable (The Wild Hunt, led by Skull Valkyrie). A mythological war — the chosen warriors vs the destructive hunters. The winner claims the AEGIS LEAGUE.', 'Active', '2025-01-01');
INSERT INTO storylines (storylineID, name, promotionID, type, worker1, worker2, description, status, startDate) VALUES (21, 'The Shieldmaiden's Trial', 6, 'Mentorship', 6001, 6003, 'Freya Asagiri has taken Hikari Tonegawa under her wing. But the AEGIS LEAGUE tournament demands that only one can win. Can their friendship survive the competition? The Shieldmaidens tag team is tested.', 'Active', '2025-01-01');

-- ============================================================
-- MATCH STORIES (8 match story templates)
-- ============================================================

INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (1, 'Standard Singles Match', 'A standard one-on-one singles match with pinfall or submission finish.', 'Singles', '[{"phase": "Opening", "text": "Both wrestlers circle each other cautiously, feeling out their opponent''s stance and rhythm."}, {"phase": "Opening", "text": "A collar-and-elbow tie-up leads to a clean break in the corner. The crowd appreciates the sportsmanship."}, {"phase": "Middle", "text": "The pace quickens as both competitors exchange holds and reversals, each trying to gain the upper hand."}, {"phase": "Middle", "text": "A high-impact move sends one wrestler to the outside, drawing a count from the referee."}, {"phase": "Climax", "text": "The challenger hits their signature move! The champion kicks out at two and a half \u2014 the crowd erupts!"}, {"phase": "Finish", "text": "In a final burst of energy, the victor hits their finisher and covers for the three-count. The bell rings."}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (2, 'Hardcore Brawl', 'A no-disqualification match with weapons and brawling.', 'Hardcore', '[{"phase": "Opening", "text": "The bell rings and both wrestlers immediately charge at each other, trading forearms and chops."}, {"phase": "Opening", "text": "A steel chair is introduced into the ring. The crowd roars in anticipation."}, {"phase": "Middle", "text": "The fight spills to the outside, with both wrestlers brawling through the crowd and over the barricade."}, {"phase": "Middle", "text": "A table is set up at ringside. The tension builds as both competitors eye the precarious weapon."}, {"phase": "Climax", "text": "A devastating weapon shot connects! The victim is bleeding heavily but refuses to stay down."}, {"phase": "Finish", "text": "The winner crashes their opponent through the table with a brutal finisher. The referee counts the pin on the floor."}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (3, 'Tag Team Match', 'A standard tag team match with hot tags and double-team moves.', 'Tag', '[{"phase": "Opening", "text": "The face team starts strong, isolating the heel''s weaker partner with quick tags and double-team offense."}, {"phase": "Middle", "text": "The heels cheat to gain control, with the legal man distracting the referee while his partner chokes the face on the ropes."}, {"phase": "Middle", "text": "The face in peril desperately crawls toward their corner, fighting through the heel''s isolation tactics."}, {"phase": "Climax", "text": "HOT TAG! The crowd explodes as the fresh face enters the ring and clears house with a flurry of offense."}, {"phase": "Finish", "text": "The faces hit their signature double-team move on the legal heel. The pin is academic \u2014 one, two, three!"}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (4, 'Lucha Libre Match', 'A high-flying lucha libre match with dives and rapid exchanges.', 'Lucha Libre', '[{"phase": "Opening", "text": "Both luchadores exchange rapid arm drags and headscissors, each trying to out-speed the other."}, {"phase": "Middle", "text": "A breathtaking sequence of flips and reversals brings the crowd to their feet."}, {"phase": "Middle", "text": "The action spills outside with a spectacular tope suicida! Both wrestlers crash into the barricade."}, {"phase": "Climax", "text": "Back in the ring, a hurricanrana from the top rope gets a near fall that the crowd can''t believe."}, {"phase": "Finish", "text": "The victor hits a picture-perfect springboard splash for the pin. The crowd chants their name as they celebrate."}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (5, 'Monster Squash', 'A dominant performance by a monster heel against an enhancement talent.', 'Squash', '[{"phase": "Opening", "text": "The monster heel stares down the enhancement talent, who visibly gulps in fear."}, {"phase": "Middle", "text": "A massive clothesline turns the enhancement talent inside out. The crowd gasps at the impact."}, {"phase": "Climax", "text": "The monster hits their devastating finisher with authority. The pin is a formality."}, {"phase": "Finish", "text": "One, two, three. The match is over in under two minutes. The monster stands dominant."}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (6, 'Championship Match', 'A high-stakes championship match with near falls and dramatic kickouts.', 'Championship', '[{"phase": "Opening", "text": "The champion and challenger stand face to face as the referee holds the championship belt high. The crowd is electric."}, {"phase": "Middle", "text": "Both competitors pull out all the stops, trading signature moves and near falls that have the crowd on the edge of their seats."}, {"phase": "Middle", "text": "The challenger hits the champion''s own finisher against them! The crowd holds its breath \u2014 but the champion kicks out at the very last second!"}, {"phase": "Climax", "text": "The champion rallies with a burst of adrenaline, hitting their signature combination. The challenger is reeling."}, {"phase": "Finish", "text": "The champion hits their finisher \u2014 the referee counts one, two, THREE! The champion retains! The crowd erupts in celebration."}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (7, 'Mask vs Mask (Luchastica)', 'The most dramatic match in lucha libre — the loser loses their mask.', 'Stipulation', '[{"phase": "Opening", "text": "Both masked luchadores stand in their corners, hands trembling. The crowd is silent with anticipation. This is more than a match \u2014 it''s a fight for identity."}, {"phase": "Middle", "text": "The match is brutal from the start. Both wrestlers know that losing their mask means losing their persona, their legacy, their self."}, {"phase": "Middle", "text": "A bloody exchange on the outside leaves both luchadores battered. Masks are torn but still on."}, {"phase": "Climax", "text": "The ruda tries to unmask the technica illegally, but the referee catches it. The crowd boos the attempted dishonor."}, {"phase": "Finish", "text": "The technica hits a breathtaking move from the top rope. The pin is counted. The loser''s mask is removed. The crowd weeps as a new face is revealed for the first time."}]');
INSERT INTO matchstories (matchstoryID, name, description, matchType, textBeats) VALUES (8, 'Iron Man Match', 'A 30-minute iron man match with multiple falls.', 'Iron Man', '[{"phase": "Opening", "text": "The timekeeper announces 30 minutes on the clock. Both wrestlers nod. This is a marathon, not a sprint."}, {"phase": "Middle", "text": "The first fall goes to the heel via a cheap pin. The crowd boos. Score: 1-0."}, {"phase": "Middle", "text": "The face rallies back with a submission hold. Score: 1-1. The crowd is alive."}, {"phase": "Climax", "text": "With five minutes remaining, the score is tied 2-2. Both wrestlers are exhausted but refuse to quit."}, {"phase": "Finish", "text": "In the final 30 seconds, one wrestler hits a desperate roll-up. The referee counts \u2014 one, two, THREE! The buzzer sounds. Final score: 3-2. The crowd explodes."}]');

-- ============================================================
-- ANGLE TEMPLATES (15 templates)
-- ============================================================

INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (1, 'Champion's Address', 'The champion comes to the ring to address the crowd and their next challenger.', 'Promo', 1, '[Worker1] stands in the center of the ring, championship belt over their shoulder. The crowd cheers as they grab the microphone. ''I''ve beaten every challenger they''ve put in front of me,'' [Worker1] declares. ''And at [Event], I''ll beat one more.'' The champion''s confidence radiates through the arena as they stare down the entrance ramp, waiting for their next opponent to emerge.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (2, 'Surprise Attack', 'A heel attacks a face from behind during an interview or promo.', 'Attack', 2, '[Worker1] is mid-interview when suddenly [Worker2] attacks from behind! A vicious clothesline sends [Worker1] crashing to the mat. [Worker2] stands over their fallen opponent, taunting the crowd. Officials rush to pull [Worker2] away as [Worker1] clutches their injured [body part].');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (3, 'Face-to-Face Confrontation', 'Two rivals stand face to face in the ring before a big match.', 'Confrontation', 2, 'The crowd is electric as [Worker1] and [Worker2] stand nose to nose in the center of the ring. The tension is palpable. [Worker1] grabs the mic: ''I''ve waited my whole career for this moment.'' [Worker2] snatches the mic: ''Then let''s make it a moment you''ll never forget.'' They shove each other as officials rush to separate them before the brawl starts.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (4, 'Championship Celebration', 'A newly crowned champion celebrates with the crowd.', 'Celebration', 1, 'Confetti rains down as [Worker1] stands on the turnbuckles, championship belt held high above their head. The crowd is on their feet, cheering wildly. [Worker1] jumps down and embraces their supporters at ringside. This is the culmination of a lifelong dream — and the beginning of a new reign.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (5, 'Backstage Ambush', 'A heel ambushes a face backstage before their match.', 'Backstage', 2, '[Worker1] is warming up backstage when [Worker2] bursts through the door with a steel chair. CRACK! The chair connects with [Worker1]''s back. [Worker2] stands over the fallen [Worker1]: ''You''re not making it to your match tonight.'' Officials and trainers rush in as [Worker2] walks away smiling.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (6, 'Stable Formation', 'A new stable is formed when multiple wrestlers unite.', 'Confrontation', 3, 'The crowd is stunned as [Worker1], [Worker2], and [Worker3] stand together in the ring. [Worker1] speaks: ''We''ve been fighting each other for too long. Tonight, we unite. Together, we are unstoppable.'' The three wrestlers raise their fists in unison as the crowd reacts — some cheering, some booing. A new power has been born in the promotion.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (7, 'Betrayal', 'A tag team partner turns on their partner.', 'Betrayal', 2, '[Worker1] and [Worker2] have just won a hard-fought match. As [Worker1] turns to celebrate, [Worker2] grabs them from behind and hits their finisher! The crowd is in shock. [Worker2] stands over their former partner with a cold expression. ''I''ve been carrying you for too long,'' [Worker2] says. ''It''s time I shine on my own.''');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (8, 'Mask Unmasking', 'A ruda attempts to unmask a technica during a promo.', 'Attack', 2, '[Worker1] (ruda) has [Worker2] (technica) trapped in the corner. [Worker1] reaches for [Worker2]''s mask, slowly peeling it back. The crowd screams in horror. ''Let''s see who you really are!'' [Worker1] taunts. Officials rush in before the mask comes fully off, but the damage is done — the sacred mask has been violated.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (9, 'Call-Up Announcement', 'A B-brand worker is announced for a call-up to the A-brand.', 'Promo', 2, 'The crowd erupts as [Worker1] (B-brand ace) is called to the ring. The A-brand ace, [Worker2], is already there. [Worker2] extends a hand: ''You''ve earned your shot. Welcome to [A-brand].'' [Worker1] shakes the hand, but the crowd senses tension — will they be friends or rivals?');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (10, 'Contract Signing', 'Two rivals sign the contract for their upcoming match.', 'Confrontation', 2, 'A table is set up in the ring with two chairs and a contract. [Worker1] signs first, slamming the pen down. [Worker2] picks up the pen, looks at [Worker1], and signs. Then [Worker2] flips the table! The contract goes flying as both wrestlers start brawling. Security rushes in to pull them apart.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (11, 'Farewell Address', 'A retiring wrestler gives their farewell speech.', 'Promo', 1, '[Worker1] stands in the ring, visibly emotional. The crowd chants their name. ''I''ve given everything to this business,'' [Worker1] says, voice breaking. ''Every bump, every bruise, every moment — I wouldn''t change a thing. Thank you for letting me live my dream.'' The crowd gives a standing ovation as [Worker1] takes a final bow.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (12, 'Heel Turn', 'A face worker turns heel after a frustrating loss.', 'Betrayal', 2, '[Worker1] has just lost a match to [Worker2]. [Worker1] sits in the corner, head in hands. The crowd encourages them. But [Worker1] slowly rises, grabs a steel chair, and CRACK — drives it into [Worker2]''s skull. The crowd is stunned into silence. [Worker1] stands over [Worker2] with a cold, dead expression. ''No more nice guy.''');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (13, 'Title Vacate', 'A champion is forced to vacate their title due to injury.', 'Promo', 1, '[Worker1] stands in the ring with the championship belt and a microphone. The crowd is hushed. ''I never thought I''d have to say this,'' [Worker1] begins, voice cracking. ''But due to my injury, I can no longer compete. I am vacating this championship.'' [Worker1] places the belt on the mat and walks away. The crowd weeps.');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (14, 'Return from Injury', 'A wrestler makes a surprise return from injury.', 'Promo', 1, 'The crowd is watching a promo when suddenly — [Worker1]''s music hits! The arena explodes as [Worker1] walks out from the back, healthy and ready. [Worker1] runs to the ring, slides under the ropes, and grabs the mic. ''Did you miss me? I''m back, and I''m coming for everything!''');
INSERT INTO angleTemplates (angleTemplateID, name, description, type, workerSlots, textTemplate) VALUES (15, 'Stable Disintegration', 'A stable breaks apart from internal conflict.', 'Betrayal', 3, 'In the ring, [Worker1] (stable leader) berates [Worker2] and [Worker3] for recent failures. ''You two have been dead weight!'' [Worker2] snaps back: ''Maybe the problem isn''t us — maybe it''s your leadership.'' [Worker3] nods in agreement. The stable explodes into a three-way brawl. The faction is dead.');

-- ============================================================
-- TEMPLATE BEATS (29 beats)
-- ============================================================

INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (1, 1, 'Champion', 'The champion enters with the belt', '[Worker1] makes their entrance, championship belt gleaming under the arena lights.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (2, 1, 'Promo', 'The champion cuts a promo', '[Worker1] grabs the microphone and addresses the crowd: ''I am the champion, and I will remain the champion.''', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (3, 1, 'Challenge', 'The champion''s challenger appears', 'Suddenly, [Worker1]''s opponent''s music hits! The crowd turns to the entrance ramp.', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (4, 2, 'Victim', 'The victim is being interviewed', '[Worker1] is being interviewed backstage, discussing their upcoming match.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (5, 2, 'Attacker', 'The attacker strikes', 'Without warning, [Worker2] attacks from behind with a devastating clothesline!', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (6, 2, 'Aftermath', 'Officials break it up', 'Officials and referees rush in to pull [Worker2] away from the fallen [Worker1].', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (7, 3, 'Face1', 'The first wrestler enters', '[Worker1]''s music hits. They walk to the ring with purpose, mic already in hand.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (8, 3, 'Face2', 'The second wrestler enters', '[Worker2]''s music interrupts! The crowd erupts as the rival makes their way to the ring.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (9, 3, 'Staredown', 'The two rivals face off', 'Nose to nose in the center of the ring. The crowd is electric. Words are exchanged.', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (10, 3, 'Shove', 'The confrontation escalates', 'A shove! Then a counter-shove! Officials rush in before it becomes a full brawl.', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (11, 4, 'Victor', 'The champion celebrates', '[Worker1] climbs the turnbuckles, championship held high. The crowd cheers wildly.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (12, 4, 'Crowd', 'The crowd shows their appreciation', 'The crowd chants [Worker1]''s name as confetti rains down from the rafters.', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (13, 5, 'Victim', 'The victim is warming up', '[Worker1] is stretching backstage, focused on their upcoming match.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (14, 5, 'Ambusher', 'The ambush happens', '[Worker2] bursts in with a weapon! CRACK! [Worker1] goes down hard.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (15, 5, 'Taunt', 'The ambusher taunts', '[Worker2] stands over [Worker1]: ''Good luck tonight. Oh wait — you''re not going to make it.''', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (16, 6, 'Leader', 'The leader speaks', '[Worker1] stands in the center of the ring: ''Tonight, we are one. Together, we are unstoppable.''', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (17, 6, 'Member1', 'The first member joins', '[Worker2] stands beside [Worker1], arms crossed. The crowd reacts.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (18, 6, 'Member2', 'The second member joins', '[Worker3] takes their place on the other side. The trio raises their fists together.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (19, 7, 'Partner1', 'The partner who gets betrayed', '[Worker1] celebrates their tag team victory, turning to embrace [Worker2].', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (20, 7, 'Partner2', 'The betrayer strikes', 'But [Worker2] hits [Worker1] with their finisher! The crowd is in absolute shock!', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (21, 7, 'Speech', 'The betrayer explains', '[Worker2]: ''I''ve been carrying you. It''s my time now.'' The crowd boos relentlessly.', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (22, 8, 'Ruda', 'The ruda traps the technica', '[Worker1] (ruda) has [Worker2] (technica) trapped in the corner, reaching for their mask.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (23, 8, 'Technica', 'The mask is nearly removed', '[Worker2] desperately fights back, trying to protect their sacred mask. The crowd screams.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (24, 8, 'Save', 'Officials intervene', 'The referee and officials pull [Worker1] away before the mask comes fully off.', 0);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (25, 9, 'B-Brand', 'The B-brand worker is called up', '[Worker1] (Fenikkusu ace) stands in the ring as the crowd chants their name.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (26, 9, 'A-Brand', 'The A-brand ace welcomes them', '[Worker2] (Doragon ace) enters and extends a hand: ''Welcome. Now prove you belong here.''', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (27, 10, 'Signer1', 'The first wrestler signs', '[Worker1] sits down and signs the contract with a slam of the pen.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (28, 10, 'Signer2', 'The second wrestler signs', '[Worker2] picks up the pen, stares at [Worker1], and signs slowly.', 1);
INSERT INTO templateBeats (beatID, templateID, slot, description, text, workerRequired) VALUES (29, 10, 'Brawl', 'The table flip and brawl', '[Worker2] flips the table! Both wrestlers start brawling as security rushes in.', 0);

-- ============================================================
-- SUMMARY
-- ============================================================

-- Storylines:      21 storylines across 6 promotions
-- Match Stories:  8 match story templates
-- Angle Templates: 15 angle templates
-- Template Beats: 29 template beats
--
-- Total: 73 content entries
